name: deploy

on:
  workflow_dispatch:
    inputs:
      envdev:
        description: 'Choisir environnement de déploiement'
        required: true
        default: 'dev'

jobs:
  First_Job:
    name: first_job
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "Démarrage du workflow sur ${{github.ref}}"
      
      - name: Checkout
        uses: actions/checkout@v4.1.1
        if: ${{github.ref == 'refs/heads/main'}}

      - name: Déploiement production
        run: echo "Déploiement production"
        if: github.event.inputs.envdev == 'prod'

      - name: Déploiement dev
        run: echo "Déploiement développement"
        if: github.event.inputs.envdev == 'dev'

      - name: Déploiement quali
        run: echo "Déploiement qualité"
        if: github.event.inputs.envdev == 'quali'
          
        
